#!/bin/bash
# vim: ts=4 et

sjcam=/opt/sjcam
sjcserver=$sjcam/bin/sjcserver
cfgbase=$sjcam/etc/gsjc/sjcserver
logdir=/srv/log
piddir=/var/run/sjcam

case "$1" in
    gsjc1|gsjc2)
        cfgfile=$cfgbase-$1.ini
        pidfile=$piddir/$1.pid
        $sjcserver -c $cfgfile >> $logdir/$1.log 2>&1 &
        echo $! > $pidfile
        ;;
    *)
        echo "Usage: $(basename $0) <gsjcX>"
        exit 1
esac
